# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.provision "docker"
  config.vm.network :private_network, ip: "172.17.42.254"
  config.vm.hostname = "dockerhost"
  config.hostsupdater.aliases = ["dockerhooost", "dockerhoooooooooooost"]

  config.vm.provision "shell", inline:
    "echo 'DOCKER_NETWORK_OPTIONS=\"-H unix:///var/run/docker.sock -H tcp://0.0.0.0:4243\"' >>/etc/sysconfig/docker-network; systemctl restart docker"

  config.vm.provision "shell", inline:
    "yum -y install bzip2 net-tools mlocate"

  config.vm.provision "shell", inline:
    "updatedb&"

  config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
end

